class TechnicalWordList {
  List<String> suggestions = [
    "accelerated graphics port (agp)",
    "acceptable use policy (aup)",
    "access control list (acl)",
    "access point (ap)",
    "account",
    "activate",
    "ad hoc network",
    "adaptor",
    "add-on",
    "address bar",
    "address resolution protocol (arp)",
    "adware",
    "affiliate",
    "alert box",
    "algorithm",
    "alignment",
    "alphanumeric",
    "alt key",
    "analog",
    "analog-to-digital converter (adc)",
    "android",
    "antivirus",
    "apple",
    "applet",
    "application",
    "application programming interface (api)",
    "archive",
    "arithmetic logic unit (alu)",
    "array",
    "artificial intelligence (ai)",
    "assembler",
    "assembly language",
    "assistive technology",
    "asymmetric digital subscriber line (adsl)",
    "attachment",
    "authenticate",
    "authoring tool",
    "automatic document feeder (adf)",
    "autoresponder",
    "avatar",
    "backbone",
    "backlink",
    "backspace",
    "backup",
    "bandwidth",
    "bare metal",
    "base station",
    "basic input/output system (bios)",
    "batch file",
    "batch processes",
    "benchmark",
    "beta software",
    "bezel",
    "big data",
    "binary",
    "bing",
    "biometrics",
    "bit",
    "bitmap",
    "bitrate",
    "bits per second (bps)",
    "bittorrent",
    "blacklist",
    "blind carbon copy (bcc)",
    "blog",
    "bluetooth",
    "bold",
    "bookmark",
    "boolean",
    "boot",
    "boot disk",
    "boot sector",
    "boot sequence",
    "bootstrap",
    "bot",
    "",
    "bridge",
    "broadband",
    "broadcast",
    "brouter",
    "browse",
    "browser",
    "buffer",
    "buffer",
    "bug",
    "built-in",
    "burn",
    "bus",
    "bus topology",
    "button",
    "byte",
    "c",
    "c++",
    "cable",
    "cable modem",
    "cache",
    "cancel",
    "caps lock",
    "captcha",
    "carbon copy (cc)",
    "careware",
    "cascading style sheet (css)",
    "casting",
    "cathode ray tube (crt)",
    "cell",
    "censorware",
    "central processing unit (cpu)",
    "character",
    "character code",
    "character encoding",
    "character map",
    "character mapping",
    "character set",
    "checkpoint",
    "checksum",
    "chip",
    "circuit",
    "clean install",
    "click",
    "client",
    "client server model",
    "clipboard",
    "clock cycle",
    "clock speed",
    "cloud computing",
    "coaxial",
    "coded character set",
    "codeview",
    "cold boot",
    "collaborative software",
    "collision",
    "column",
    "command (cmd)",
    "command interpreter",
    "command line interface (cli)",
    "command prompt (cmd.exe)",
    "commercial software",
    "common development and distribution license (cddl)",
    "common internet file system (cifs)",
    "communications software (cs)",
    "compact disc file system (cdfs)",
    "compact disc read-only memory (cd-rom)",
    "compact disc re-writable (cd-rw)",
    "compact disc-recordable (cd-r)",
    "compact disk (cd)",
    "compatibility",
    "compile",
    "compiler",
    "compiler bug",
    "component software",
    "compression",
    "computational linguistics",
    "computer",
    "computer ethics",
    "computer game",
    "computer networking",
    "computer science",
    "computer software",
    "configuration",
    "configuration files  (config)",
    "configuration management",
    "connectivity devices",
    "console",
    "constant bit rate (cbr)",
    "content management system (cms)",
    "control panel",
    "controller card",
    "cookie",
    "copy",
    "copier",
    "copycat",
    "copyright",
    "crash",
    "cronjob",
    "crop",
    "cross browser",
    "cross platform",
    "cryptography",
    "cursor",
    "cut",
    "cyberbullying",
    "cybercrime",
    "cybersecurity",
    "data",
    "data definition language (ddl)",
    "data management",
    "data transfer rate (dtr)",
    "data type",
    "database",
    "database management system (dbms)",
    "datagram",
    "dcim",
    "debug",
    "debugger",
    "default",
    "default program",
    "defragment",
    "delete",
    "desktop",
    "desktop publishing",
    "developer",
    "dial up",
    "dialog box",
    "digital",
    "digital signature",
    "digital versatile disc (dvd)",
    "digital-to-analog converter (dac)",
    "digitize",
    "direct memory access (dma)",
    "directory",
    "disk",
    "disk image",
    "document",
    "domain name",
    "domain name system (dns)",
    "donation ware",
    "dongle",
    "dots per inch (dpi)",
    "double click",
    "download",
    "drag",
    "drag and drop",
    "drive",
    "driver",
    "drop down menu",
    "dual boot",
    "dual-core processor",
    "duplex",
    "dynamic host configuration protocol (dhcp)",
    "dynamic websites",
    "earphone",
    "e-book reader (e-reader)",
    "electronic book (ebook)",
    "electronic data interchange (edi)",
    "electronic learning (e-learning)",
    "electronic mail (email)",
    "electronic-commerce (e-commerce)",
    "email bomb",
    "emoji",
    "encoding",
    "encryption",
    "end user",
    "enter key",
    "error correction code (ecc)",
    "escape key",
    "ethernet",
    "even number",
    "excel",
    "executable",
    "execute",
    "expansion card",
    "export",
    "extensible",
    "external hard drive",
    "facebook",
    "favicon",
    "fiber optic cable",
    "field",
    "file",
    "file association",
    "file extension",
    "file format",
    "file server",
    "file system",
    "file transfer protocol (ftp)",
    "file type",
    "filename",
    "firewall",
    "firmware",
    "first in",
    "flash drive",
    "flowchart",
    "folder",
    "font",
    "footer",
    "format",
    "formula",
    "fragmentation",
    "frame",
    "frames per second (fps)",
    "framework",
    "freeware",
    "frequently asked question (faq)",
    "full duplex",
    "function",
    "gateway",
    "geographic information systems(gis)",
    "gigabit",
    "gigabyte",
    "gigahertz (ghz)",
    "google",
    "google drive",
    "graphical user interface (gui)",
    "graphics",
    "graphics processing unit (gpu)",
    "grep",
    "grid computing",
    "hacker",
    "hard copy",
    "hard disk",
    "hard drive",
    "hardware",
    "header",
    "headphone",
    "heat sink and fan (hsf)",
    "hertz",
    "hibernate",
    "high-definition multimedia interface (hdmi)",
    "hit",
    "home page",
    "host",
    "hotfix",
    "hover",
    "hub",
    "hyperlink",
    "hypertext",
    "hypertext markup languagge (html)",
    "hypertext preprocessor (php)",
    "hypertext transfer protocol (http)",
    "icloud",
    "icon",
    "import",
    "inbox",
    "information and communication technologies (ict)",
    "information technology (it)",
    "input",
    "input device",
    "instagram",
    "install",
    "institute of electrical and electronics engineers (ieee)",
    "integer",
    "integrated circuit (ic)",
    "interface",
    "internet",
    "internet connection sharing (ics)",
    "internet corporation for assigned names and numbers. (icann)",
    "internet information services (iis)",
    "internet protocol (ip)",
    "internet protocol address (ip address)",
    "internet protocol verison 4 (ipv4)",
    "internet protocol verison 6 (ipv6)",
    "internet service provider (isp)",
    "intranet",
    "ipad",
    "iphone",
    "iphone operating system (ios)",
    "ipod",
    "itunes",
    "java",
    "joystick",
    "kernel",
    "keyboard",
    "keyboard shortcut",
    "keylogger",
    "keystrokes",
    "keyword",
    "keyword",
    "kilobytes",
    "landscape",
    "laptop",
    "laser printer",
    "left-click",
    "light-emitting diode (led)",
    "link",
    "linkedin",
    "linux",
    "liquid crystal display (lcd)",
    "local area network (lan)",
    "localhost",
    "log file",
    "login",
    "logoff",
    "logon",
    "logout",
    "loop",
    "macintosh computers operating system (mac os)",
    "macro",
    "mail server",
    "malware",
    "margin",
    "markup language",
    "master boot record (mbr)",
    "matrix",
    "maximize",
    "media access control address (mac address)",
    "megabyte",
    "megapixel",
    "memory",
    "memory card",
    "menu bar",
    "metadata",
    "microblogging",
    "micrometer",
    "microphone",
    "microsecond",
    "milimeter",
    "milisecond",
    "minimize",
    "mirror",
    "mobile",
    "modem",
    "monitor",
    "motherboard",
    "mount",
    "mouse",
    "mouse pad",
    "multimedia",
    "multiprocessing",
    "multitasking",
    "myspace",
    "mysql",
    "nagware",
    "nanometer",
    "nanosecond",
    "natural language processing (nlp)",
    "nerd",
    "netiquette",
    "network",
    "network access point (nap)",
    "network interface card (nic)",
    "network operations center (noc)",
    "network topology",
    "neural network",
    "newbie",
    "newline (\n)",
    "newsfeed",
    "nickname",
    "node",
    "noise",
    "non-proprietary software (nps)",
    "nonvolatile memory",
    "notebook",
    "nudge",
    "null",
    "num lock",
    "numeric keypad",
    "odd number",
    "offline",
    "online",
    "online service",
    "open",
    "open source",
    "operating system (os)",
    "optical carrier",
    "optical carrier",
    "optical character recognition (ocr)",
    "oracle database",
    "orientation",
    "outbox",
    "outliner",
    "output",
    "output device",
    "overwrite",
    "packet",
    "page fault",
    "page layout",
    "page view",
    "paint",
    "parallel computing",
    "parallel processing",
    "parity",
    "parser",
    "partition",
    "password",
    "paste",
    "patch",
    "path",
    "peripheral",
    "permalink",
    "personal computer (pc)",
    "phishing",
    "photocopier",
    "picometer",
    "picosecond",
    "ping",
    "piracy",
    "pixel",
    "plagiarism",
    "platform",
    "plug and play",
    "plug-in",
    "point to point protocol (ppp)",
    "polyfont recognition",
    "pop-up",
    "port",
    "portable software",
    "portrait",
    "post",
    "power button",
    "power management unit (pmu)",
    "power on self -test (post)",
    "primary key",
    "primary memory",
    "printer",
    "printer control language  (pcl)",
    "printout",
    "procedure",
    "process",
    "process",
    "process identifier (pid)",
    "processor",
    "program",
    "programmer",
    "programming language",
    "prompt",
    "proprietary software",
    "protocol",
    "proxy server",
    "public-domain software",
    "pull",
    "push",
    "python",
    "qr code",
    "quality",
    "query",
    "query language",
    "query optimizer",
    "queue",
    "quicktime",
    "quit",
    "random access memory (ram)",
    "raw data",
    "raw file",
    "read only",
    "readme file",
    "read-only memory (rom)",
    "real time",
    "record",
    "record length",
    "record type",
    "recursion",
    "recycle bin",
    "redo",
    "redundancy",
    "refresh",
    "register",
    "registry",
    "regular expression",
    "relational database (rd)",
    "remote",
    "remote access",
    "remote desktop",
    "remote user",
    "repeater",
    "resolution",
    "response",
    "responsive web design (rwd)",
    "restore",
    "rich text",
    "right click",
    "root",
    "root directory",
    "router",
    "routing",
    "row",
    "rtf editor",
    "run",
    "runtime",
    "safe mode",
    "sandwich test",
    "scanner",
    "scareware",
    "screen",
    "screen recording",
    "screencast",
    "screenshot",
    "scroll",
    "scrollbar",
    "search engine",
    "secondary memory",
    "secondary storage",
    "sector",
    "secure shell (ssh)",
    "segment",
    "semiconductor",
    "server",
    "server application",
    "service",
    "service pack",
    "service set identifier (ssid)",
    "session",
    "set",
    "shareware",
    "shell",
    "shift key",
    "short message service (sms)",
    "sidebar",
    "simple mail transfer protocol (smpt)",
    "simulation",
    "site map",
    "sleep",
    "smartphone",
    "smiley",
    "social media",
    "social media marketing (smm)",
    "social software",
    "socket",
    "soft copy",
    "software",
    "software audit",
    "software blacklist",
    "software cracking",
    "software development kit",
    "software engineer (se)",
    "software engineering",
    "software entropy",
    "software environment",
    "software genre",
    "software hoarding",
    "software license",
    "software life-cycle",
    "software metric",
    "software package",
    "software piracy",
    "software project life cycle",
    "software rot",
    "software theft",
    "software tool",
    "sort",
    "sound card",
    "source code",
    "spam",
    "speaker",
    "speech recognition",
    "spell checker",
    "spoofing",
    "spool",
    "spreadsheet",
    "spyware",
    "ssl certificate",
    "stack",
    "stand-alone",
    "standby",
    "start menu",
    "static website",
    "status bar",
    "storage",
    "streaming",
    "string",
    "structured analysis",
    "structured query language (sql)",
    "subdirectory",
    "subject",
    "subnet mask",
    "subscript",
    "super computer",
    "superscript",
    "surf",
    "swap file",
    "swipe",
    "switch",
    "switch",
    "symmetric digital subscriber line (sdsl)",
    "sync",
    "syntax",
    "syntax error",
    "system administrator (sysadmin )",
    "system analyst",
    "system software",
    "systray",
    "tab",
    "tab",
    "table",
    "tablet",
    "tag",
    "task bar",
    "task scheduling",
    "technology services",
    "telecomputing",
    "teleconference",
    "telemedicine",
    "template",
    "terabyte",
    "terahertz",
    "terminal",
    "text box",
    "text editor",
    "thumbnail",
    "title bar",
    "toggle key",
    "toolbar",
    "tooltip",
    "torrent",
    "touch screen",
    "touchpad",
    "transfer",
    "transmission control protocol  (tcp)",
    "trash",
    "tree",
    "trigger",
    "trojan horse",
    "troubleshoot",
    "truncate",
    "tutorial",
    "tweet",
    "twitter",
    "typecasting",
    "typeface",
    "undo",
    "unfriend",
    "unicode",
    "uniform resource locator (url)",
    "uninterruptible power supply (ups)",
    "universal serial bus (usb)",
    "unix",
    "unmount",
    "unzip",
    "upgrade",
    "upload",
    "user",
    "user acceptance testing (uat)",
    "user friendly",
    "user id",
    "username",
    "utility program",
    "variable",
    "vector graphic",
    "video card",
    "video game",
    "viral",
    "virtual",
    "virtual learning environment (vle)",
    "virtual memory system  (vms)",
    "virtual private network (vpn)",
    "virus",
    "volume",
    "wide area network(wan)",
    "wavelength",
    "web address",
    "web application",
    "web authoring",
    "web design",
    "web development",
    "web forum",
    "web host",
    "web page",
    "webcam",
    "webmail",
    "webmaster",
    "website",
    "whitelist",
    "widget",
    "wi-fi",
    "wiki",
    "window",
    "windows",
    "winzip",
    "wired",
    "wireless",
    "wireless access point",
    "wizard",
    "word processing",
    "word art",
    "wordpress",
    "wordwrap",
    "workspace",
    "workstation",
    "world wide web (www)",
    "world wide web consortium (w3c)",
    "worm",
    "write",
    "yahoo",
    "youtube",
    "zipping",
    "zoom",
    "zoom in",
    "zoom out",
    "2d",
    "3d",
    "absolute advantage",
    "abstract",
    "abstract",
    "accelerator principle",
    "acceptable",
    "acceptance",
    "accommodation",
    "accommodation bill",
    "account",
    "account",
    "account  current",
    "account balance",
    "account book",
    "account holders name",
    "account number",
    "account of expenditure",
    "accountancy",
    "accountant",
    "accounting",
    "accounting course",
    "accounting manual",
    "accounting principles",
    "accounting standard",
    "accounting system",
    "accounts",
    "accounts assistant",
    "accounts bureau",
    "accounts division",
    "accounts officer",
    "accrual accounting",
    "accumulation unit",
    "acquisition",
    "acquisition of shares",
    "acquisition price",
    "actively managed fund",
    "activity",
    "actual cost",
    "actual expense",
    "actual price",
    "actuary",
    "add",
    "addition",
    "additional payment",
    "addressee",
    "adequate",
    "adequately",
    "adjunct",
    "adjust",
    "adjustable rate mortgage (arm)",
    "adjusted gross income (agi)",
    "adjustments",
    "adjustor",
    "administer",
    "administered prices",
    "administration",
    "administration fees and charges",
    "administrative block",
    "administrative costs",
    "administrative fees and charges",
    "adoption process",
    "advance",
    "advance",
    "advance deposit slip",
    "advanced",
    "advance-decline (a-d) line",
    "advancement",
    "advertise",
    "advertisement",
    "advertisement fee",
    "advertiser",
    "advertising",
    "advertising agent",
    "advertising media",
    "after-hours market",
    "after-tax income",
    "agent",
    "agent bank",
    "aggregate",
    "aggregate demand curve.",
    "aggregate expenditure",
    "aggregate supply curve",
    "aggressive-growth fund",
    "aggrieved",
    "agree",
    "agreement",
    "agriculture",
    "agriculture machinery",
    "agriculture product",
    "aid",
    "aid",
    "aid and debt management manual",
    "alimony",
    "allocate",
    "allocation",
    "allocation of fund",
    "allotment",
    "allowance",
    "alternative minimum tax (amt)",
    "amount",
    "annual",
    "annual account",
    "annual administrative report",
    "annual budget",
    "annual financial statement",
    "annual national budget",
    "annual percentage rate",
    "annual percentage yield",
    "annual plan",
    "annual renewable term insurance",
    "annual report",
    "annual review",
    "annually",
    "annuitant",
    "annuity",
    "annuity unit",
    "anticipated expenditure",
    "anticipated income",
    "apportionment",
    "appraisal",
    "appraise",
    "appraisement",
    "appraiser",
    "appropriation",
    "approved charge",
    "approver",
    "approximate",
    "approximately",
    "approximation",
    "arrears",
    "assess",
    "assessment",
    "assessment efforts",
    "assessment unit",
    "assessor",
    "asset",
    "asset allocation",
    "asset management account (ama)",
    "asset management company (amc)",
    "asset securitisation",
    "asset turnover",
    "assist",
    "assistance",
    "assistant",
    "assistant accounts officer",
    "assistant budget officer",
    "assistant internal auditor",
    "assistant procurement officer",
    "auction",
    "auction and record",
    "auctioner",
    "auctions",
    "audit",
    "audit",
    "audit clearance",
    "audit recoveries accounts",
    "audit report",
    "auditor",
    "auditor general",
    "authorized depository",
    "automated teller machine (atm)",
    "automated teller machine card (atm card)",
    "automation",
    "average",
    "average",
    "average",
    "average cost",
    "average fixed costs",
    "average revenue",
    "average revenue product",
    "average variable costs",
    "avoidance",
    "bad debt",
    "balance",
    "balance",
    "balance fund",
    "balance of payment",
    "balance of payments account",
    "balance of trade",
    "balance sheet",
    "bank",
    "bank account",
    "bank balance",
    "bank book",
    "bank card",
    "bank charges",
    "bank credit",
    "bank draft",
    "bank guarantee",
    "bank holiday",
    "bank loan",
    "bank note",
    "bank overdraft",
    "bank rate",
    "bank reconciliation statement",
    "bank statement",
    "bank statement",
    "banker",
    "banking",
    "banking company",
    "banking facilities",
    "banking service",
    "bankrupt",
    "bankruptcy",
    "bankruptcy act",
    "bar",
    "barber",
    "barber shop",
    "bargain",
    "bargain",
    "bartender",
    "barter",
    "barter system",
    "base cost",
    "base rate",
    "base year",
    "basic pay",
    "bearer",
    "bearer bond",
    "behaviour segmentation",
    "beneficial",
    "beneficial owner",
    "beneficiary",
    "benefit",
    "benefit",
    "bid",
    "bid",
    "bid form",
    "bid price",
    "bidder",
    "bidding",
    "bilateral monopoly",
    "bill",
    "bill",
    "bill broker",
    "bill of entry",
    "bill of exchange",
    "bill of indemnity",
    "bill of lading",
    "bill of sale",
    "billion",
    "billionaire",
    "bin card",
    "black economy",
    "black market",
    "black marketeer",
    "black money",
    "block account",
    "block currency",
    "block grants",
    "block trade",
    "blue collar",
    "board of directors",
    "bond",
    "bond fund",
    "bond insurance",
    "bond paper",
    "bond rating",
    "bond swap",
    "bonus",
    "bonus shares",
    "book entry",
    "book keeping",
    "book of account",
    "book value",
    "book value per share",
    "bookkeeper",
    "bookkeeping",
    "books of account",
    "boom",
    "boom",
    "borrow",
    "borrower",
    "borrowing",
    "borrowing power",
    "bottom-up investing",
    "brand",
    "brand ambassdor",
    "brand associations",
    "brand awareness",
    "brand equity",
    "brand image",
    "brand loyalty",
    "brand name",
    "brand new",
    "brand position",
    "branded",
    "breakeven",
    "bridging loan",
    "broad head",
    "broker",
    "brokerage",
    "brokerage account",
    "brokerage firm",
    "brokerage window",
    "brokering",
    "bucket-shop",
    "budget",
    "budget allocation",
    "budget analyst",
    "budget approval",
    "budget assistant",
    "budget call",
    "budget concepts and principles",
    "budget cycle",
    "budget deficit",
    "budget estimate",
    "budget fund account",
    "budget head",
    "budget line",
    "budget manual",
    "budget model",
    "budget notification",
    "budget officer",
    "budget outlay",
    "budget presentation",
    "budget process",
    "budget proposal",
    "budget provision",
    "budget re-appropriation",
    "budget recommendation",
    "budget report",
    "budget review",
    "budget specialist",
    "budget summary",
    "budget withdrawal",
    "budgetary bodies",
    "budgetary releases",
    "budgetary support",
    "budgeting management division",
    "budgeting system",
    "building",
    "building material",
    "bulk buying",
    "bullion market",
    "business",
    "business agent",
    "business and professional licenses",
    "business cycle",
    "business document",
    "business hours",
    "business income tax",
    "business license",
    "business planning",
    "business risks",
    "business tax",
    "businessman",
    "businesswoman",
    "buy",
    "buy and sell orders",
    "buyback",
    "buyer",
    "buyer power",
    "buyer’s market",
    "buying",
    "by product pricing",
    "by-product",
    "call money",
    "capital",
    "capital account",
    "capital budget",
    "capital consumption",
    "capital consumption allowance",
    "capital cost",
    "capital employed",
    "capital expenditure",
    "capital gain",
    "capital goods",
    "capital grants",
    "capital income",
    "capital investment",
    "capital labour ratio",
    "capital items",
    "capital loss",
    "capital output ratio",
    "capital recovery factor",
    "capital release",
    "capital reserves",
    "capital revenue",
    "capital surplus",
    "capital value",
    "capitalism",
    "capitalist",
    "capitalist class",
    "capitalistic",
    "capitalization",
    "capitalize",
    "cargo",
    "cargo plane",
    "cargo vessel",
    "carriage",
    "cash",
    "cash accounting",
    "cash advance",
    "cash and kind",
    "cash balance",
    "cash book",
    "cash box",
    "cash counter",
    "cash credit",
    "cash credit account",
    "cash crop",
    "cash deposit slip",
    "cash desk",
    "cash dispenser",
    "cash flow",
    "cash flow per share",
    "cash flow statement",
    "cash grant",
    "cash income",
    "cash inflow",
    "cash machine",
    "cash payment",
    "cash point",
    "cash reserve",
    "cash reserve ratio",
    "cash starved",
    "cash transaction",
    "cash warrant",
    "cashier",
    "cattle tax",
    "central bank",
    "central inventory",
    "centralism",
    "centralize",
    "certificate of deposit (cd)",
    "chain store",
    "change in demand",
    "charge",
    "chargeable income",
    "charges",
    "charity",
    "charity shop",
    "chart of accounts",
    "cheap",
    "cheapjack",
    "cheaply",
    "cheapness",
    "cheque",
    "cheque book",
    "cheque collection",
    "chequebook",
    "claim",
    "claim",
    "claimant",
    "claims in arrears",
    "classical economics",
    "clearing agent",
    "clerance sale",
    "client",
    "client agency",
    "closing stock",
    "co-funding",
    "coin",
    "coin(25 chhetrum)",
    "coin(50 chhetrum)",
    "collateral",
    "collateral security",
    "collections",
    "collective ownership",
    "collector’s item",
    "combined leverage",
    "commerce",
    "commercial",
    "commercial banks",
    "commercial loan",
    "commercial paper",
    "commercial traveler",
    "commercialization",
    "commercially",
    "commission",
    "committed loans",
    "commodity",
    "common market",
    "common stock",
    "company",
    "comparative",
    "comparative advantage",
    "compensate",
    "compensation",
    "compensatory",
    "compete",
    "competition",
    "competitive",
    "competitive advantage",
    "competitive firm",
    "competitor",
    "compliance auditing",
    "complementary",
    "complementary goods",
    "composition of indirect tax",
    "compound",
    "compound interest",
    "compulsory labour",
    "computer and peripherals",
    "concession",
    "concession period",
    "concessionaire",
    "concessional loan",
    "concessionary",
    "confiscable",
    "confiscate",
    "confiscation",
    "confiscator",
    "consignee",
    "consignment",
    "consignor",
    "consolidated accounts",
    "consolidated fund",
    "consortium",
    "conspicuous consumption",
    "constant dollars",
    "construct",
    "construction",
    "construction manager",
    "constructional",
    "constructor",
    "consultancy",
    "consultant",
    "consultant fee",
    "consultation",
    "consultative",
    "consumable",
    "consume",
    "consumer",
    "consumer behaviour",
    "consumer durables",
    "consumer goods",
    "consumer market",
    "consumer price index",
    "consumer protection",
    "consumer surplus",
    "consumerism",
    "consumption",
    "consumption function",
    "consumption income ratio",
    "consumption spending",
    "contingencies",
    "contingency fund",
    "contingency plan",
    "contingency reserve",
    "contingent liabilities",
    "contract",
    "contractor",
    "contribute",
    "contribution",
    "contributor",
    "contributory",
    "convenience goods",
    "convenience product",
    "convenience store",
    "convert",
    "convertible",
    "convertible currencies",
    "convertible preference shares",
    "cook shop",
    "co-operative",
    "co-owner",
    "copyright",
    "corner shop",
    "corporate",
    "corporate finance",
    "corporate income tax",
    "corporation",
    "corporation tax",
    "cost",
    "cost",
    "cost accounting",
    "cost benefit",
    "cost control",
    "cost cutting",
    "cost effective",
    "cost function",
    "cost index",
    "cost of debentures",
    "cost of goods sold (cogs)",
    "cost of living",
    "cost of production",
    "cost of sales (cos)",
    "cost price",
    "costing",
    "costliness",
    "costly",
    "cottage",
    "cottage cheese",
    "cottage hospital",
    "cottage industry",
    "council tax",
    "counter signs",
    "countermand",
    "counterpart",
    "countersign",
    "coupon",
    "court-fee",
    "credit",
    "credit bureau",
    "credit card",
    "credit note",
    "credit policy",
    "credit report",
    "creditor",
    "cross check",
    "cross cheque",
    "cumulative preference shares",
    "currency",
    "current",
    "current account",
    "current assets",
    "current expenditure",
    "current fiscal year",
    "current grants",
    "current liabilities",
    "current ratio",
    "current regular releases",
    "current yield",
    "custody",
    "custody of government money",
    "custom duty",
    "custom tax",
    "customer advances",
    "customer service",
    "customer service desk",
    "customs",
    "customs declaration",
    "daily allowance",
    "daily subsistence allowance",
    "daily wage",
    "damages",
    "data",
    "deadline",
    "dealer",
    "debenture",
    "debenture stock",
    "debit",
    "debt",
    "debt and liabilities management",
    "debt equity ratio",
    "debt service",
    "debt service ratio",
    "debtor",
    "deciders",
    "decline",
    "decrease",
    "deduct",
    "default",
    "default risk",
    "defect liability period",
    "deficit",
    "define",
    "deflate",
    "deflation",
    "delinquent borrower",
    "delinquent loan",
    "delivery",
    "delivery form",
    "demand",
    "demand curve",
    "demand deposits",
    "demand draft",
    "demographic",
    "demographic segmentation",
    "demography",
    "department store",
    "deposit",
    "deposit",
    "deposit invoice",
    "deposit money",
    "deposit slip",
    "deposit works",
    "depositor's name",
    "depot surcharge",
    "depreciate",
    "depreciation",
    "derived demand",
    "desire",
    "detention memo",
    "devaluation",
    "devalue",
    "deviations",
    "difficulty allowance",
    "diminishing return",
    "direct cost",
    "direct mail marketing",
    "direct selling",
    "direct spending",
    "direct tax",
    "disburse",
    "disbursement",
    "disbursement voucher",
    "discount",
    "discount",
    "discount bond",
    "discount period",
    "discretionary",
    "discriminatory pricing",
    "disinvestments",
    "dispose off",
    "distillery",
    "distillery products",
    "distribute",
    "distribution",
    "distribution channel",
    "distributor",
    "diversification",
    "diversion of fund",
    "divestment",
    "divide",
    "dividend",
    "dividend income",
    "dividend payout ratio",
    "dividend yield",
    "division",
    "domestic credit",
    "domestic industry",
    "domestic market",
    "domestic resource",
    "domestic revenue",
    "donate",
    "donation",
    "donor",
    "double check",
    "double decker",
    "double entry system",
    "double taxation",
    "draft",
    "draw",
    "drawee",
    "drawer",
    "due",
    "dumpling policy",
    "duopoly",
    "duopsony",
    "durable",
    "durable goods",
    "duty",
    "duty free",
    "earn",
    "earnest money",
    "earning",
    "earnings per share",
    "earnings yield",
    "easy money",
    "economic",
    "economic activity",
    "economic backwardness",
    "economic classification",
    "economic cooperation",
    "economic development",
    "economic imperialism",
    "economic power",
    "economic prospect",
    "economic recession",
    "economic reform",
    "economic self-reliance",
    "economic standard",
    "economic viability",
    "economics",
    "economies of scale",
    "economies of scope",
    "economise",
    "economist",
    "economy",
    "elastic demand",
    "elastic supply",
    "elasticity",
    "embargo",
    "emergency goods",
    "employ",
    "employee",
    "employer",
    "employment",
    "emporium",
    "encash",
    "encashment",
    "endorsee",
    "endorsement",
    "endorsement in blank",
    "endorsement in full",
    "endorser",
    "endow",
    "endowment",
    "enlist",
    "enquiry fee",
    "entertain",
    "entertainer",
    "entertainment",
    "entertainment expense",
    "entertainment tax",
    "entitle",
    "entitlement",
    "entitlement limit",
    "environmental surcharge",
    "equation",
    "equilibrium",
    "equipment",
    "equity",
    "equity finance",
    "equity portfolio",
    "equity share",
    "equity share capital",
    "equity shareholder",
    "escrow account",
    "estate",
    "estate agent",
    "estimate",
    "estimated cost",
    "estimation",
    "exchange",
    "exchange rate",
    "exchangeable",
    "exchequer",
    "excise",
    "excise and duties",
    "excise duty on distillery products",
    "excise duty refund",
    "exempt",
    "exemption",
    "exemption certificate",
    "expend",
    "expenditure",
    "expenditure outlay",
    "expense",
    "expense account",
    "expensive",
    "explicit cost",
    "exploratory research",
    "export",
    "export",
    "export duty",
    "export finance",
    "export product",
    "export tariff",
    "export tax",
    "exportable",
    "exportation",
    "exporter",
    "external",
    "external funding",
    "external market",
    "external reserves",
    "external sources",
    "extra",
    "extra",
    "extra price",
    "face value",
    "factory",
    "family pension",
    "fare",
    "fast food",
    "feasibility",
    "fee",
    "acceptance certificate",
    "final tax",
    "finance",
    "finances",
    "financial",
    "financial adviser",
    "financial assistance",
    "financial auditing",
    "financial company",
    "financial consultant",
    "financial expert",
    "financial feasibility",
    "financial institution",
    "financial leverage",
    "financial management",
    "financial management manual",
    "financial planner",
    "financial resource",
    "financial service",
    "financial specialist",
    "financial strength",
    "financial year",
    "financier",
    "financing",
    "financing gap",
    "fine",
    "fine",
    "fine",
    "finished product",
    "fire insurance",
    "firm",
    "fiscal",
    "fiscal agent",
    "fiscal bulletin",
    "fiscal deficit",
    "fiscal policy",
    "fiscal year",
    "fish monger",
    "five year plan",
    "fixed assets",
    "fixed capital",
    "fixed costs",
    "fixed deposit",
    "fixed price",
    "fixed-term",
    "flagship project",
    "flat rate",
    "flea market",
    "flesh mongar",
    "float",
    "floating capital",
    "floating charge",
    "floating debt",
    "focus group",
    "food",
    "food and drink",
    "food and raiment",
    "food grains",
    "food processor",
    "food stuffs",
    "forced labour",
    "forecast",
    "forecast",
    "forecasting",
    "foreclosure",
    "foreign",
    "foreign allowance",
    "foreign currency",
    "foreign direct investment",
    "foreign exchange",
    "foreign exchange rate",
    "foreign investment",
    "foreign product",
    "foreign reserve",
    "forfeit",
    "forfeiture",
    "forms",
    "formula",
    "forward estimates",
    "franchise",
    "free",
    "free port",
    "free trade",
    "full tax liability",
    "functional classification",
    "fund",
    "fund balance",
    "fund raising",
    "fundamental analysis",
    "funder",
    "funding",
    "furniture",
    "gain",
    "gainful",
    "gate money",
    "general store",
    "gift",
    "global market",
    "goods",
    "goodwill",
    "government bond",
    "government exchequer",
    "government securities",
    "grand total",
    "grant",
    "gratis",
    "gratis",
    "gratuity",
    "gross",
    "gross domestic product",
    "gross income",
    "gross international reserves",
    "gross national happiness",
    "gross national product",
    "gross profit",
    "group insurance scheme",
    "growth",
    "growth rate",
    "guarantee",
    "guarantor",
    "haggle",
    "half-price",
    "handling charges",
    "handout",
    "hard cash",
    "hard currency",
    "hard sell",
    "hawk",
    "hawker",
    "hazard insurance",
    "health contribution",
    "health insurance",
    "heavy industry",
    "heavy-duty",
    "hedge fund",
    "high priced",
    "high risk",
    "hire",
    "hire purchase",
    "hoard",
    "hoarder",
    "holder",
    "holding",
    "holding tax",
    "honorarium",
    "house tax",
    "housing  project",
    "housing estate",
    "housing insurance",
    "hype",
    "hypothecate",
    "hypothecation",
    "immeasurable",
    "immovable property",
    "implicit costs",
    "import",
    "import duty",
    "import licence",
    "imported item",
    "importer",
    "imprest",
    "impulses goods",
    "incalculable",
    "inchoate stamped instrument",
    "incidentals",
    "income",
    "income statement",
    "income support",
    "income tax",
    "income year",
    "incorrect",
    "increase",
    "increment",
    "indebted",
    "indemnity",
    "indent",
    "index",
    "indicators",
    "indirect cost",
    "indirect tax",
    "individual tax",
    "industrial",
    "industrial action",
    "industrial arts",
    "industrial economy",
    "industrial estate",
    "industrial market",
    "industrial plot shed rent",
    "industrial property",
    "industrialist",
    "industrialization",
    "industrialize",
    "industry",
    "industry rank",
    "inexpensive",
    "inflation",
    "inflation rate",
    "inflation risk",
    "inflationary",
    "inflow",
    "infrastructure",
    "inherit",
    "inheritance",
    "inherited",
    "inheritor",
    "initial cost",
    "initial investment",
    "initiators",
    "inland instrument",
    "input",
    "insolvent",
    "installment",
    "installment credit",
    "instant payment",
    "instrument payable on demand",
    "instruments",
    "insurable",
    "insurance",
    "insurance company",
    "insurance policy",
    "insurance premium",
    "insurant",
    "insure",
    "insured",
    "insurer",
    "intangible",
    "intangible property",
    "integrate",
    "integration",
    "intellectual property",
    "intellectual property right",
    "intensive distribution",
    "interest",
    "interest free",
    "interest free loan",
    "interest income",
    "interest payment",
    "interest rate",
    "interim",
    "interim receiver",
    "internal audit",
    "internal check",
    "internal control",
    "internal market",
    "internal revenue",
    "internal sources",
    "internal trade",
    "international",
    "international market",
    "international money transfer",
    "international statutory monetary agencies",
    "international stock market",
    "international trade fair",
    "internet based selling",
    "invalid",
    "invalidate",
    "invaluable",
    "inventories",
    "inventory",
    "invest",
    "investment",
    "investor",
    "invoice",
    "iron manger",
    "issue",
    "issued share capital",
    "issuer",
    "item",
    "joint",
    "joint collector",
    "joint venture",
    "journal book",
    "journal voucher",
    "journals",
    "jumble sale",
    "junk bond",
    "justification",
    "label",
    "labor",
    "labor force",
    "laboratory",
    "labour market",
    "lapsed fund",
    "large company",
    "law merchant",
    "law of demand",
    "law of return",
    "law of supply",
    "lease",
    "lease",
    "lease agreement",
    "leasehold",
    "ledger",
    "legal advisor",
    "legal aid",
    "legal tender",
    "lend",
    "lender",
    "lending",
    "lending rate",
    "lessee",
    "lessor",
    "letter of credit",
    "letters of guarantee",
    "level",
    "levy",
    "levy",
    "liabilities",
    "liability",
    "liable",
    "lien",
    "life insurance",
    "light industry",
    "limit order",
    "limited",
    "limited company",
    "limited liability",
    "limited partnership",
    "limited resource",
    "limited resource financing",
    "limited tax liability",
    "line agencies",
    "line of credit",
    "liquidate",
    "liquidation",
    "liquidation of accounts",
    "liquidator",
    "liquidity",
    "liquidity ratio",
    "liquor tax",
    "list",
    "listed company",
    "living trust",
    "living wage",
    "loan",
    "loan",
    "loan division",
    "loan shark",
    "local market",
    "local tax",
    "logbook",
    "long term financing",
    "logistics",
    "losses and defalcation",
    "lottery division",
    "lottery scheme section",
    "low risk",
    "low value asset",
    "lower price",
    "lucrative",
    "lump sum contract",
    "lump sum payment",
    "luxury items",
    "machine",
    "macro economic framework",
    "macro economics",
    "maintenance cost",
    "maintenance fund",
    "maintenance of property-building",
    "maintenance of property-computers",
    "maintenance of property-equipment",
    "maintenance of property-plantations",
    "maintenance of property-vehicle",
    "mandate",
    "mandate documents",
    "manpower",
    "manual",
    "manufactory",
    "manufacture",
    "manufacture",
    "manufactured products",
    "manufacturer",
    "manufacturing",
    "marginal cost",
    "market",
    "market capitalization",
    "market force",
    "market order",
    "market place",
    "market price",
    "market rate",
    "market rent",
    "market research",
    "market risk",
    "market share",
    "market value",
    "market vendor fee",
    "marketable",
    "marketing",
    "marketing audit",
    "marketing control",
    "marketing myopia",
    "marketing orientation",
    "marketing personnel",
    "marketing plan",
    "mark-up pricing",
    "mart",
    "mass produce",
    "mass production",
    "massage parlour",
    "master plan",
    "material",
    "materialism",
    "materialist",
    "materialistic",
    "mature",
    "maturity",
    "means",
    "measure",
    "measurement",
    "measurement book",
    "medium company",
    "medium term financing",
    "mega",
    "mega project",
    "megabucks",
    "memo",
    "memorandum",
    "menu",
    "mercantile",
    "mercantile system",
    "merchandise",
    "merchant",
    "merchant bank",
    "merchant marine",
    "merchant navy",
    "merchantable",
    "merchantship",
    "mid year budget review",
    "middlemen",
    "million",
    "millionaire",
    "millionaires",
    "minimum wage",
    "miscalculate",
    "miscalculation",
    "miscellaneous",
    "miscellaneous costs",
    "mixed economy",
    "mobilization",
    "monetary",
    "monetary assistance",
    "monetary economy",
    "monetize",
    "money",
    "money box",
    "money maker",
    "money order",
    "money supply",
    "moneyed",
    "moneylender",
    "money-market",
    "monger",
    "monopolise",
    "monopolist",
    "monopoly",
    "monopoly power",
    "monopsony",
    "monthly allowance",
    "monthly recovery",
    "mortgage",
    "mortgage",
    "mortgage broker",
    "mortgage-backed security",
    "mortgagee",
    "mortgagor",
    "motor vehicle tax",
    "movable property",
    "moral right",
    "multi year fiscal framework",
    "multi year rolling budget",
    "multilateral",
    "multinational",
    "multinational marketing",
    "multiple-choice",
    "municipal tax",
    "muster rolls",
    "national debt",
    "national exchequer",
    "national income",
    "national market",
    "natural resource",
    "necessity",
    "need",
    "needs",
    "needy",
    "negative balance",
    "negoitator",
    "negotiable",
    "negotiable instrument",
    "negotiate",
    "negotiations",
    "net",
    "net assets (also called total net assets)",
    "net cash flow",
    "net current assets",
    "net income",
    "net interest",
    "net lending",
    "net payment",
    "net present value (npv)",
    "net price",
    "net profit",
    "net profit margin",
    "net sales",
    "net taxable income",
    "net worth",
    "news agent",
    "nominal value",
    "non disclosure agreement",
    "non plan",
    "non profit organization",
    "non revenue",
    "non tax revenue",
    "non-consumable",
    "non-durable goods",
    "non-payment",
    "non-profit",
    "non-refundable",
    "non-revenue release",
    "non-tax revenue",
    "novelty",
    "note",
    "object",
    "object classification",
    "object code",
    "object of expenditure",
    "off-budget",
    "offer",
    "office equipments",
    "official sign",
    "off-licence",
    "old-age pension",
    "oligopoly",
    "open market",
    "opening stock",
    "operating cash flow",
    "operating cost",
    "operating costs and expenses",
    "operating expense",
    "operating income",
    "operating leverage",
    "operating margin",
    "operational expenditure",
    "opportunity cost",
    "opposition",
    "optimal",
    "optimum profit",
    "option",
    "ordinary share",
    "original",
    "out bid",
    "out goings",
    "out lay",
    "outcome",
    "outdated",
    "outlet",
    "output",
    "output labour ratio",
    "outstanding",
    "outstanding debt",
    "over capatilize",
    "over charge",
    "over value",
    "overall",
    "overall volume of trade",
    "overdraft",
    "overdraw",
    "overdue",
    "overhead costs",
    "overheads",
    "overpayment",
    "overpriced",
    "owe",
    "owner",
    "ownerless",
    "ownership",
    "paper currency",
    "paper money",
    "paper shop",
    "par value",
    "part exchange",
    "parties",
    "partner",
    "partnership",
    "part-time",
    "pass",
    "passive debt",
    "patent",
    "patentable invention",
    "pawn",
    "pawn broker",
    "pawnshop",
    "pay",
    "pay bills",
    "pay off",
    "pay severance",
    "payable",
    "payback period",
    "payee",
    "payer",
    "paying cabin",
    "payments",
    "payout ratio",
    "payroll",
    "pays and allowances",
    "pecuniary",
    "peddle",
    "pelf",
    "penal interest",
    "penalty",
    "pension",
    "pensioners",
    "per annum",
    "per capita",
    "per capita income",
    "perceived value pricing",
    "percentage",
    "perfect competition",
    "perfect market",
    "performance auditing",
    "performance based budgeting",
    "performance indicators",
    "permanent advance",
    "permanent working capital",
    "permit",
    "personal allowance",
    "personal and general trade",
    "personal emoluments",
    "personal income tax",
    "petty",
    "petty cash",
    "petty contract",
    "petty contractor",
    "phase",
    "physical assets management",
    "psychological factor",
    "piece rate",
    "pittance",
    "plan",
    "planner",
    "planning",
    "plant",
    "plant and machineries",
    "pledge",
    "plus",
    "pocket money",
    "point of sale",
    "political economy",
    "poll tax",
    "pony charge",
    "pool",
    "pool budget",
    "possession",
    "post free",
    "post paid",
    "postage",
    "postal order (money order)",
    "power tax",
    "preference share capital",
    "preferred share",
    "preferred stock",
    "pre-financing",
    "premium",
    "premium bond",
    "prepaid",
    "present value",
    "preserve fund",
    "press",
    "press agent",
    "prevailing cost",
    "price",
    "price drop",
    "price fixing",
    "price tag",
    "price war",
    "price-earnings ratio (p/e)",
    "priceless",
    "pricing policy",
    "primary",
    "primary co-operatives",
    "primary data",
    "primary research",
    "prime cost",
    "principal",
    "principal and interest",
    "prior year adjustments",
    "prior year advances",
    "private",
    "private company",
    "private enterprise",
    "proceeds",
    "process",
    "processing",
    "processor",
    "procure",
    "procurement",
    "procurement management process",
    "procurer",
    "produce",
    "producer",
    "product",
    "product class",
    "product line",
    "product quality",
    "product type",
    "product width",
    "production",
    "production capacity",
    "production cost",
    "production department",
    "production function",
    "production method",
    "production shed",
    "productive",
    "productivity",
    "professional license tax",
    "profit and loss",
    "profit and loss account (p and l)",
    "profit margin",
    "profitable",
    "profiteer",
    "profitless",
    "profits",
    "profit maximisation",
    "profit-sharing",
    "program grants",
    "project",
    "project approval",
    "project charter",
    "project costs",
    "project finance",
    "project grants",
    "project management",
    "project proposal",
    "project resource plan",
    "project risk",
    "project tied borrowing",
    "project tied grants",
    "projection",
    "project-tied borrowing",
    "promissory note",
    "promote",
    "promoter",
    "property",
    "property tax",
    "property transfer tax",
    "proprietor",
    "proprietorship",
    "propulsion charges",
    "prospectus",
    "provident fund",
    "provision",
    "provisional tax",
    "prudent fiscal policy",
    "psychological factors",
    "psychological pricing",
    "public",
    "public",
    "public auction",
    "public company",
    "public corporation",
    "public enterprise section",
    "public enterprises",
    "public finance",
    "public fund",
    "public house",
    "public housing",
    "public limited company",
    "public procurement",
    "public procurement policy division",
    "public property",
    "public purse",
    "publicity agent",
    "purchase",
    "purchase",
    "purchase of power",
    "purchaser",
    "purchasing policy",
    "purchasing power",
    "put option",
    "qualitative",
    "quality",
    "quality control",
    "quantitative",
    "quantitative restriction",
    "quantity",
    "quick ratio",
    "quota",
    "quotation",
    "quote",
    "rate",
    "rate",
    "rate of return",
    "raw material",
    "ready money",
    "real estate",
    "real property",
    "real rate of return",
    "realignment",
    "re-appropriation",
    "rebate",
    "receipt",
    "receipt and payments",
    "receipts",
    "recession",
    "reconcile",
    "reconciliation",
    "recoveries",
    "recovery",
    "recovery of outstanding loan",
    "re-current budget",
    "recurrent expenditure",
    "reflation",
    "refund",
    "refundable deposit accounts",
    "refundable deposits",
    "registration",
    "registration fee",
    "reimburse",
    "reimbursement",
    "related rights",
    "relief fund",
    "remainder",
    "remaining",
    "remittance",
    "remitter",
    "remunerate",
    "remuneration",
    "renewal fee",
    "rent",
    "rental expense",
    "rental income",
    "rental of properties",
    "repay",
    "repayment",
    "requisite budget forms",
    "reserve",
    "reserve fund",
    "reserves",
    "resource",
    "resource allocations",
    "resource envelope",
    "resource gap",
    "restoration",
    "restitution",
    "restricted funds",
    "retail",
    "retailer",
    "retailment",
    "retention money",
    "retirement benefits",
    "return",
    "return on capital employed (roce)",
    "return on equity (roe)",
    "return on investment",
    "revaluation",
    "revenue",
    "revenue accounts and audit",
    "revenue audit and investigation",
    "revenue forecasting",
    "revenue manual",
    "revenue receipts",
    "review budget",
    "revise",
    "revised budget",
    "revolving funds",
    "revocation",
    "reward",
    "risk",
    "risk",
    "risk audit",
    "risk based auditing",
    "risk trade-off",
    "road tax",
    "rolling budget",
    "royalty",
    "royalty income",
    "running bills",
    "running expenses",
    "rural",
    "rural development",
    "rural development scheme",
    "rural enterprise",
    "rural life insurance",
    "rural tax",
    "safe",
    "safety",
    "salary",
    "salary income",
    "salary saving scheme",
    "salary tax",
    "sale",
    "sale proceeds",
    "saleable",
    "sale-deed",
    "salemanship",
    "saleroom",
    "sales clerk",
    "sales management",
    "sales operation",
    "sales planning",
    "sales promotion",
    "sales slip",
    "sales talk",
    "sales tax",
    "sales turnover",
    "salesman",
    "salesperson",
    "salvage value",
    "sanction",
    "sanctioning officer",
    "safeguard measure",
    "saving",
    "saving deposit",
    "savings bank",
    "scale",
    "scrutiny",
    "sealed bid pricing",
    "sealed tender bid",
    "search",
    "seating fees",
    "secondary data",
    "sectoral revenue",
    "secured advance",
    "security",
    "security money",
    "seed capital",
    "seed money",
    "self employed",
    "self-assessed tax",
    "self-financing ratio",
    "sell",
    "seller",
    "selling",
    "selling price",
    "sell-off",
    "sell-out",
    "semi-finished",
    "service",
    "service charge",
    "service tax",
    "settle",
    "settled",
    "settlement",
    "share",
    "share broker",
    "share capital",
    "share holder",
    "share market",
    "shareholder's equity",
    "shareholder's funds",
    "shoestring",
    "shop",
    "shop assistant",
    "shop floor",
    "shopkeeper",
    "shopper",
    "shopping",
    "shopping centre",
    "shopping goods",
    "shopping mall",
    "short term financing",
    "show business",
    "silver",
    "silver coin",
    "simple interest",
    "site plan fee",
    "skimming price policy",
    "small scale",
    "social",
    "social and economic reform",
    "socio economic development",
    "socio-economic",
    "soft goods",
    "soft loan",
    "source",
    "source of finance",
    "source of income",
    "source of revenue",
    "special allowance",
    "special fund",
    "special type of co-operatives",
    "spend",
    "spending",
    "spillover",
    "spot cash",
    "stage",
    "stakeholder",
    "stale or time barred cheque",
    "stamp duty",
    "staple goods",
    "statement",
    "status",
    "stipends",
    "stock",
    "stock broker",
    "stock exchange",
    "stock market",
    "stock holder",
    "stock-in-trade",
    "storage",
    "storage charges",
    "store",
    "store house",
    "structure",
    "structure of budget",
    "structure of interest rates",
    "sub contarct",
    "subcontractor",
    "subscription",
    "subsidiary",
    "subsidiary company",
    "subsidy",
    "subsidies and countervailing duties",
    "subsist",
    "subsistance allowance",
    "subsistence",
    "supermarket",
    "supplement",
    "supplementary budget",
    "supplier",
    "supplier power",
    "supply",
    "supply curve",
    "supply and demand",
    "supply and materials",
    "surcharge",
    "surety",
    "surplus",
    "surplus",
    "suspense account",
    "syndicate",
    "syndication",
    "system auditing",
    "system of accounting",
    "take-home pay",
    "tangible",
    "tap rate",
    "target",
    "tariff",
    "tariff concesssion",
    "schedule of concession",
    "tariffication",
    "tax",
    "tax assessment",
    "tax bracket",
    "tax break",
    "tax clearance certificate",
    "tax collector",
    "tax deducted at source (tds)",
    "tax deductible",
    "tax dodge",
    "tax dodger",
    "tax evasion",
    "tax exempt",
    "tax free",
    "tax haven",
    "tax holiday",
    "tax in cash",
    "tax in kind",
    "tax liability",
    "tax officer",
    "tax payer",
    "tax rate",
    "tax relief",
    "tax return",
    "tax revenue",
    "tax shelter",
    "taxable income",
    "taxpayer",
    "tea shop",
    "technical",
    "technical adjustments",
    "technical assistance",
    "technology",
    "telemarketing",
    "teller",
    "temporary advance",
    "tender",
    "tender documents",
    "third country-import unit",
    "ticket",
    "time barred cheque",
    "time barred claims/adjustments",
    "time barred payment",
    "token",
    "toll-free",
    "top ten revenue agencies",
    "top-up",
    "total adjusted gross income",
    "total assets",
    "total cost",
    "total fixed cost",
    "trade",
    "trade agreement",
    "trade balance",
    "trade classification",
    "trade circle",
    "trade credit",
    "trade deficit",
    "trade embargo",
    "trade facilitation",
    "electronic commerce",
    "trade fair",
    "trade firm",
    "non discrimination",
    "most favoured nation",
    "national treatment",
    "freedom to trade",
    "trade development committee",
    "industry classification",
    "transit trade",
    "certificate of origin",
    "certification mark",
    "tarrif rate quota",
    "trade in goods",
    "trade in service",
    "trade license",
    "trade name",
    "trade price",
    "trade relation",
    "trade route",
    "trade sale",
    "trade secret",
    "trade show",
    "trade union",
    "trademark",
    "trading",
    "transaction",
    "transaction costs",
    "transfer",
    "transferee",
    "transferor",
    "travel agent",
    "travel allowance",
    "traveller’s cheques",
    "treasurer",
    "treasury bill (t-bill)",
    "treasury bond (t-bond)",
    "treasury note (t-note)",
    "trial balance",
    "trillion",
    "trust",
    "trust deed",
    "trust fund",
    "trustee",
    "turnover",
    "under development land tax",
    "under paid",
    "underfunded",
    "union co-operatives",
    "urban house tax",
    "user charges",
    "user fee",
    "users",
    "vicarious approach",
    "valuable",
    "valuation",
    "value",
    "value",
    "value added tax",
    "valueless",
    "variable cost",
    "vegetable market",
    "venture",
    "venture capital",
    "voucher",
    "wage",
    "wager",
    "want",
    "warehouse",
    "warrant",
    "wealth",
    "wealth tax",
    "white collar",
    "wholesale",
    "wholesaler",
    "withholder",
    "working capital",
    "workshop",
    "world bank",
    "world trade",
    "write off་",
    "write up",
    "yard sale",
    "yield",
    "zero based budgeting",
    "directly competitive product",
    "prior art",
    "priority date",
    "patent process",
    "substantive examination",
    "formality examination",
    "invalidation",
    "international search report",
    "international preliminary examination report",
    "cross-license",
    "utility model",
    "layout-design of integrated circuit",
    "freely negoitaited license",
    "industrial design",
    "designer",
    "international classification",
    "mark",
    "likelihood of confusion",
    "well-known marks",
    "geographical origin",
    "geographical indication",
    "armorial bearing",
    "hallmark",
    "collective mark",
    "homonymous geographical indication",
    "undisclosed information",
    "industrial or commercial espionage",
    "exclusive licence",
    "compulsory licence",
    "counterfeit goods",
    "domain name",
    "plurilateral agreement",
    "like product",
    "importer of record",
    "business enterprise award",
    "abstract",
    "acceptance",
    "account",
    "account holder's name",
    "accountant",
    "accounting",
    "acquisition",
    "activity",
    "actuary",
    "addition",
    "adequate",
    "adjunct",
    "administration and accounts division",
    "advance",
    "agent",
    "aggregate",
    "aid",
    "alimony",
    "allotment",
    "amount",
    "amount in figure",
    "amount in words",
    "annual percentage rate (apr)",
    "annual percentage yield (apy)",
    "annuitant",
    "annuity",
    "apportionment",
    "appraisal",
    "appraise",
    "arrears",
    "assess",
    "assessor",
    "assets",
    "assistance",
    "assistant procurement officer",
    "auction and record division",
    "auctions",
    "audit",
    "average",
    "bail",
    "balance",
    "balance of payments",
    "banker",
    "banking",
    "bankruptcy",
    "bargain",
    "barter",
    "base-rate",
    "bearer",
    "beneficiary",
    "benefit",
    "bhutan sales tax",
    "bid",
    "bidding",
    "bills",
    "bills of exchange",
    "bills of lading",
    "bond",
    "bonus",
    "borrow",
    "borrower",
    "borrowing",
    "breakeven",
    "broker",
    "buy",
    "buyback",
    "buyer",
    "calls",
    "cash",
    "cash prize",
    "cashier",
    "charges",
    "cheque",
    "chief accounts officer",
    "chief budget officer",
    "chief internal auditor",
    "chief procurement officer",
    "chit fund",
    "circular",
    "city bank",
    "claims",
    "contingencies",
    "cost",
    "cost-cutting",
    "cost-effective",
    "costing",
    "costliness",
    "current adhoc releases",
    "current grants-individuals/non profit organization",
    "danger money",
    "debt management division",
    "delegation of financial power",
    "department of lottery",
    "department of national budget (dnb)",
    "department of national properties (dnp)",
    "department of public account (dpa)",
    "department of revenue and custom (drc)",
    "departmental tender committee",
    "deposit",
    "depression",
    "deputy collector",
    "deviations",
    "disburse",
    "disbursement officer",
    "discount",
    "dividend",
    "division",
    "double-check",
    "drawing and disbursing officer",
    "duty-free",
    "deputy chief accounts officer",
    "deputy chief budget officer",
    "deputy chief internal auditor",
    "deputy chief procurement officer",
    "earned leave",
    "en-cash",
    "en-cashment",
    "entrusted agency",
    "entry",
    "expenditure on structure-water supply and sanitation",
    "expenditure on structure-bridges",
    "expenditure on structure-building",
    "expenditure on structure-drainage systems",
    "expenditure on structure-irrigation channel",
    "expenditure on structure-others",
    "expenditure on structure-plantation",
    "expenditure on structure-roads",
    "expenses",
    "export",
    "fake",
    "finance",
    "finance and accounts section",
    "financial",
    "financial rules and regulation",
    "fine",
    "firm",
    "fiscal",
    "fixed cost",
    "forecast",
    "forecasting",
    "foreclosure",
    "frugality",
    "full power",
    "general inventory note",
    "general receipt note (grn)",
    "goi program grants",
    "goi project grants",
    "grant",
    "gratis",
    "gratuity",
    "gross domestic product (gdp)",
    "haggle",
    "handout",
    "hawk",
    "hawker",
    "hush-money",
    "immobile property",
    "in kind assistance",
    "incentive",
    "indemnify",
    "instalment",
    "itemize",
    "jackpot",
    "journals",
    "judiciary fees and charges",
    "justification",
    "label",
    "labourer",
    "last pay certificate",
    "lavish",
    "lease",
    "leasehold",
    "leave travel concessions",
    "ledger",
    "lend",
    "lender",
    "lending",
    "lessee",
    "lessor",
    "level",
    "levy",
    "levy tax",
    "list company",
    "loan",
    "lucrative",
    "mandate",
    "manual",
    "manufacture",
    "market",
    "mart",
    "materials",
    "means",
    "mileage",
    "miscalculate",
    "miscount",
    "mobilization",
    "money",
    "monger",
    "mortgage",
    "mortgagee",
    "mortgagor",
    "national accounts and service section",
    "net",
    "note",
    "object",
    "operational expenditure-others",
    "operational expenditure in country meeting and celebration",
    "operational expenditure-advertising",
    "operational expenditure-transportation",
    "other direct tax",
    "other payments",
    "other personal emoluments",
    "other personnel emoluments",
    "other receipts",
    "other receipts and balances",
    "outcome",
    "outdated",
    "outlet",
    "output",
    "overall",
    "pass",
    "personnel emoluments",
    "plants and equipments-roads",
    "plants and equipments-general tools",
    "plants and equipments-hospital/lab. equipment",
    "plants and equipments-livestock",
    "plants and equipments-power generation",
    "plants and equipments-telecommunication",
    "གོང་ཚད་དང་ཁྱད་འབབ་ཆ་ཚད།",
    "procurement manual",
    "procurement officer",
    "procurement section",
    "projection",
    "property",
    "property management manual",
    "prospectus",
    "provision",
    "public companies",
    "quality",
    "quantity",
    "quotation",
    "rates",
    "realignment",
    "rebate",
    "receipts",
    "reconciliation",
    "recoveries",
    "release and monitoring division",
    "release and treasury division",
    "releases",
    "rentals",
    "return",
    "revise",
    "revised",
    "risk",
    "risk/return trade-off",
    "royalties",
    "supply and materials-medicines and laboratory consumables",
    "supply and materials-seeds",
    "supply and materials-office supplies",
    "salaries",
    "sales of govt. properties/ assets",
    "security/earnest money",
    "self controlling officer",
    "share holder's",
    "special allowances",
    "sr. accounts officer",
    "sr. budget officer",
    "sr. internal auditor",
    "sr. procurement officer",
    "stockbroker",
    "stockholder",
    "surety",
    "surplus",
    "target",
    "tarriff",
    "tax",
    "tax administration division",
    "tax holidays",
    "tax-deductible",
    "training budget",
    "training-others",
    "transactions",
    "transfer of fund",
    "transfer of profit",
    "travel allowance bill",
    "travel authorization",
    "travel in country",
    "treasury management division",
    "trustee",
    "turnover",
    "underwrite",
    "utilities-electricity-firewood",
    "utilities-electricity",
    "utilities-telegram",
    "utilities-telephone",
    "valuable",
    "value",
    "verification",
    "wages",
    "ware housing",
    "warrant",
    "warranty",
    "wealth",
    "written off",
    "yield",
    "abdicate",
    "abdicator",
    "abdication",
    "access  fund",
    "accounts committee",
    "ad hoc committee",
    "adjournment",
    "adjournment of meeting",
    "adjudication",
    "administrative action",
    "administrative law",
    "administrative machinery",
    "administrative tribunal",
    "admissible questions",
    "adopt",
    "adoption of minutes",
    "adult suffrage",
    "affirmation of office",
    "affirmative resolution",
    "allegation",
    "allowance",
    "alternative dispute resolution cent",
    "ambassador",
    "amend",
    "amendment",
    "amendment and authoritative text",
    "amnesty",
    "annual",
    "annual capital grant",
    "annually",
    "anti-corruption commission",
    "anti-corruption",
    "apolitical",
    "appeal",
    "appellate authority",
    "appellate committee",
    "appellant",
    "application",
    "appoint",
    "appointee",
    "appointing authority",
    "appointment",
    "appreciation",
    "appr",
    "argument",
    "article",
    "aspiration",
    "attendance",
    "attorney general",
    "authenticate",
    "authenticity",
    "authoritative text",
    "autonomy",
    "back-bencher",
    "ballot",
    "ballot box",
    "ballot machine",
    "ballot paper",
    "baseless",
    "baseless allegation",
    "basic principle",
    "benedictions",
    "bicameral",
    "bilateral",
    "bilateral relation",
    "bill",
    "bill of rights",
    "block development committee",
    "board",
    "boast",
    "body",
    "book of accounts",
    "boundaries",
    "budget discussion",
    "bureaucracy",
    "by-election",
    "by-law",
    "cabinet",
    "cabinet secretary",
    "campaign",
    "campaign financing",
    "campaigner",
    "candidate",
    "candidate representative",
    "candidature",
    "capital",
    "capital punishment",
    "caretaker government",
    "cast",
    "casting vote",
    "cause of contention",
    "chairman of board of director",
    "chairperson",
    "chairperson of the national council",
    "change",
    "charter",
    "check and balance",
    "chief election commissioner",
    "chief executive officer",
    "chief justice",
    "chief legal off",
    "citizen",
    "citizenship",
    "city",
    "civil case",
    "classification of town",
    "closed door meeting",
    "closed door session",
    "cohe",
    "collection of tax",
    "collective respo",
    "collusion",
    "comemorate events",
    "command bills",
    "commencement",
    "commissioner",
    "committee",
    "committee hearing",
    "committee stage",
    "common law",
    "common representative",
    "communal protection",
    "community development",
    "community forest",
    "community leader",
    "community representa",
    "compassion",
    "compose",
    "composition",
    "comprehension",
    "concise",
    "concurrence",
    "condition",
    "conflict of interest",
    "conscience",
    "conscientiously",
    "consensus",
    "consent",
    "con",
    "consolidated",
    "constituency",
    "constitutional body",
    "constitutional monarchy",
    "constitutional post",
    "consul",
    "consult",
    "consultative variance",
    "contempt of parliament",
    "contentious issue",
    "contraband",
    "contradicting thought",
    "contradiction",
    "convention",
    "conviction",
    "cooperative assessment organization",
    "cooperative measure",
    "corrupt practice",
    "corruption",
    "council of minister",
    "council",
    "councilor",
    "counter",
    "counter argument",
    "counting personal personnel",
    "counting representative",
    "counting staff",
    "counting supervisor",
    "court fee",
    "court of",
    "court order",
    "crime",
    "criminal",
    "criminal case",
    "criminal code",
    "crisis",
    "crown",
    "crown prince",
    "crown princess",
    "crown properties",
    "culture",
    "custodian of law",
    "custom",
    "death sentence",
    "debate",
    "debate of the house",
    "deciding election",
    "deciding vote",
    "decision making system",
    "deem fit",
    "deemed expedient",
    "defense",
    "defendant",
    "defense forces",
    "degree of crime",
    "degree of felonies",
    "deliberative vote",
    "delimitation",
    "delimitation commission",
    "delimitation officer",
    "demarcation",
    "democracy",
    "democratic constitutional monarchy",
    "democratic foundation",
    "democratic government",
    "democratic system",
    "deputation",
    "deputy chairperson",
    "deputy speaker",
    "differ",
    "direct lineal descendants",
    "director on the board of director",
    "disciplinary action",
    "disciplinary committee",
    "disclose",
    "discussion",
    "discussion session",
    "disobedience",
    "dissolution",
    "disp",
    "dispute",
    "disappointed view",
    "dissolution",
    "distortion",
    "draft bill",
    "due process of law",
    "dungkhag(sub district)",
    "dungpa(head of the sub district)",
    "dy. chairperson of the national council",
    "dy. prime minister",
    "dy. speaker",
    "dt secretary",
    "dzongdag(district administrator)",
    "dzongkhag election officer",
    "dzongkhag tshogdu",
    "dzongkhag development grant",
    "dzongrab (asst. district administrator)",
    "economic development and private sector committee",
    "elected po",
    "election",
    "election act",
    "election campaign",
    "election certificate",
    "election code of conduct",
    "election commission",
    "election commissioner",
    "election officer",
    "election",
    "election representative",
    "election symbol",
    "electoral",
    "electoral officer",
    "electoral registration officer",
    "electoral rolls",
    "electorate",
    "electronic voting machine (evm)",
    "eligibility criteria",
    "emergency",
    "eminent ju",
    "eminent person",
    "end of fiscal year",
    "environment",
    "environment and urban development committee",
    "equal access",
    "equal right",
    "equality vote",
    "equity and justice",
    "establishment",
    "ethic",
    "ex officio",
    "examination",
    "executive",
    "executive officer",
    "exec",
    "exe",
    "exercise power",
    "exit poll",
    "expel",
    "extent",
    "extraordinary",
    "extraordinary session",
    "fabricated political affair",
    "fabricated reason",
    "facilitate",
    "fair",
    "fair mann",
    "fair procedure",
    "fair trial",
    "false information",
    "final auth",
    "final budget",
    "final liberation",
    "final settlement",
    "finance committee",
    "financial manual",
    "financial powers",
    "financial procedure",
    "financial statement",
    "finger print",
    "first reading",
    "first schedule",
    "five year term",
    "flattery",
    "follow up action",
    "foreign legal agency",
    "foreign relations committee",
    "forged document",
    "formal university degree",
    "formation of government",
    "forthright",
    "free and fair",
    "free choice",
    "freedom",
    "freedom of conscience",
    "freedom of expression",
    "freedom of movement",
    "freedom of opinion",
    "freedom of press",
    "freedom of religion",
    "freedom of residence",
    "freedom of speech",
    "freedom of thought",
    "fundamental duty",
    "fundamental responsibility",
    "fundamental right",
    "fundamental rights",
    "gallery",
    "gatherings",
    "gaydrung (",
    "general election",
    "general election",
    "general round",
    "gewog",
    "gewog accountant",
    "gewog administrative officer",
    "gewog committee",
    "gewog development grant",
    "gewog tshogde",
    "goal",
    "golden throne",
    "good characteristics",
    "good governance",
    "good governance committee",
    "government bill",
    "government fund",
    "government undertaking corporation",
    "governor",
    "grass root level",
    "guarantee",
    "guardian",
    "guilt",
    "gup (head of block)",
    "head of state",
    "hereditary monarchy",
    "hereditary succession",
    "high court",
    "high level official",
    "higher position",
    "highest legislative body",
    "highest standard",
    "hindrance",
    "historic agreement",
    "holders of constitutional offices",
    "holistic approach",
    "honourable",
    "honourable member",
    "house",
    "house committee",
    "house leader",
    "house of parliament",
    "house of review",
    "house official",
    "household",
    "human rights",
    "human rights committee",
    "humanitari",
    "impeachment",
    "imprisonment",
    "incumbent",
    "industrial city",
    "influence",
    "insurance corporation",
    "interim government",
    "interim government",
    "international territorial boundary",
    "interpolation",
    "interpretation",
    "interpretation clause",
    "interrogation",
    "interval",
    "introduce",
    "introduction of bill",
    "irrevocable faith",
    "joint committee",
    "joint sitting",
    "judge",
    "judgment order",
    "judicial adjudication",
    "judicial authority",
    "judicial body",
    "judicial cadre",
    "judicial commission",
    "judicial conference",
    "judicial discretion",
    "judicial integrity",
    "judicial investigation",
    "judicial notice",
    "judicial obligation",
    "judicial operation",
    "judicial process",
    "judicial record",
    "judicial review",
    "judicial service council",
    "judicial status",
    "judiciary",
    "jurisprudence",
    "jurist",
    "justifiable economy",
    "kingdom",
    "land acquisition",
    "land transaction",
    "lapse",
    "lawful marriage",
    "lawful rule",
    "lawful trad",
    "leader of the opposition party",
    "legal action",
    "legal agreement",
    "legal assistance",
    "legal code of conduct",
    "legal expert",
    "legal heir",
    "legal justification",
    "legal matter",
    "legal opinion",
    "legal process",
    "legal provision",
    "legal representative",
    "legal right",
    "legal service",
    "legal term",
    "legal tribu",
    "legislation",
    "legislative agenda",
    "legislative assembly",
    "legislative b",
    "legislative body",
    "legislative committee",
    "legislative func",
    "legislative issue",
    "legislative procedure",
    "legislature",
    "legitimate descendant",
    "letter of intent",
    "literature",
    "litigant",
    "local arts",
    "local development plan",
    "local government",
    "local government",
    "local government act",
    "local intere",
    "lower house",
    "luminous",
    "majority of votes",
    "malfeasance",
    "manifesto",
    "martial law",
    "matter referred",
    "mayor",
    "means to connect",
    "mediation committee",
    "member",
    "member",
    "member of parliament",
    "member secretary",
    "membership fee",
    "meritorious",
    "metropolitan city",
    "mid-term review",
    "mind treasure",
    "mineral resources",
    "minimum period",
    "minister",
    "ministerial coordination meeting",
    "misdemeanor",
    "misgiving",
    "misinterpretation",
    "model bill",
    "modern system",
    "monetary system",
    "money bills",
    "monitoring and evaluation committee",
    "monuments",
    "motion of censure",
    "municipal council",
    "municipal rules",
    "municipality",
    "nation",
    "nationality",
    "national",
    "national assembly",
    "national assembly bill",
    "national assembly constituency",
    "national cohesion",
    "national council",
    "national council constituency",
    "national day",
    "national election affair",
    "national election procedure",
    "national language",
    "national referendum",
    "national referendum",
    "natura",
    "negation",
    "negotiate",
    "nepotism",
    "nine qualities",
    "nomination",
    "nomination form",
    "nomination paper",
    "non-compliance",
    "non-governmental organization",
    "non-violence",
    "notification",
    "null and void",
    "nul",
    "oath",
    "oath of allegiance",
    "oath of allegiance",
    "oath of of",
    "oath of secrecy",
    "obscene",
    "office bearer",
    "office of profit",
    "opposition leader",
    "opposition party",
    "oppression",
    "oral question",
    "order of business",
    "order of reference",
    "order paper",
    "ordinance",
    "ordinary",
    "original jurisdiction",
    "orthodox view",
    "panel discussion",
    "paramilitary structure",
    "parent act",
    "parliament",
    "parliamentarian",
    "parliamentary",
    "parliamentary constituency",
    "parliamentary delegation",
    "parliamentary library",
    "parliamentary precinct",
    "parliamentary privilege",
    "parliamentary procedure",
    "parliamentary secretary",
    "partisan",
    "party",
    "party member",
    "party president",
    "party representative",
    "party supporter",
    "party symbol",
    "passing of bills",
    "patriotic",
    "patriotism",
    "peaceful coexistence",
    "peaceful means",
    "peaceful offence",
    "penal code",
    "penal provision",
    "people",
    "people's representative",
    "periodic election",
    "permissible office",
    "petition",
    "petitioner",
    "petty misdemeanor",
    "pictorial design",
    "plaintiff",
    "plea bargain",
    "plea of not guilty",
    "politics",
    "political affilia",
    "political crisis",
    "political group",
    "political motif",
    "political parties",
    "political power",
    "political principle",
    "political rights",
    "political science",
    "political system",
    "political transition",
    "politician",
    "poll",
    "poll station",
    "polling booth",
    "polling day",
    "polling officer",
    "polling representative",
    "polling station",
    "postal",
    "postal ballot",
    "postulate",
    "power",
    "preamble",
    "prejudice",
    "preliminary",
    "president",
    "presiding officer",
    "press gallery",
    "pre-trial",
    "prevention",
    "prevention council",
    "preventive measure",
    "primary level",
    "primary round",
    "prime minister",
    "principles of state policy",
    "prison",
    "prison term",
    "private member",
    "private member's bill",
    "privilege",
    "privy council",
    "prosecutor",
    "prohibition",
    "pronounced command",
    "proper conduc",
    "property assessment committee",
    "proportionate share",
    "prorogation",
    "prosecution",
    "prosperity",
    "protection",
    "protest",
    "protocol",
    "provisional vote",
    "public accounts",
    "public accounts committee",
    "public accounts committee(joint committee)",
    "public activities",
    "public bill",
    "public broadcast",
    "public campaign finance",
    "public campaign financing",
    "public confidence",
    "public considerat",
    "public document",
    "public election",
    "public election fund",
    "public emergency",
    "public facility",
    "public issue",
    "public meeting",
    "public meeting",
    "public money",
    "public office",
    "public petition",
    "public resource",
    "public review",
    "public safety",
    "public security",
    "public servant",
    "qualification",
    "quorum",
    "rating",
    "rational",
    "reading of bill",
    "recent past",
    "recess",
    "reconsider",
    "reconvene",
    "record of meetings",
    "recording of votes",
    "recourse to jus",
    "re-deliberate",
    "reference",
    "referendum",
    "register general",
    "registrar",
    "reiterate",
    "reiteration",
    "rejection of votes",
    "repeal",
    "report",
    "report of proceedings",
    "reprimand",
    "reproach",
    "resolution of proceeding",
    "respect",
    "responsi",
    "re-state",
    "returning officer",
    "right",
    "right to education",
    "right to hold property",
    "right to information",
    "right to information of voter",
    "right to liberty",
    "right to life",
    "right to practice",
    "right to privacy",
    "right to property",
    "right to security of pe",
    "royal advisory council",
    "royal assent",
    "royal audit authority",
    "royal civil service commission",
    "royal command",
    "royal consent",
    "royal court of justice",
    "royal decree",
    "royal family",
    "royal heir",
    "royal prerogative",
    "royal recommendation",
    "rule making committee",
    "rule of law",
    "rules and regulations",
    "rules of procedure",
    "ruling party",
    "ruling power",
    "sacred duty",
    "sanctioning authority",
    "schedule",
    "screen",
    "scrutinize",
    "seal",
    "seat",
    "second",
    "second reading",
    "secret ballot",
    "secretariat",
    "secretary",
    "secretary general",
    "sectional diversit",
    "selfless",
    "seminar",
    "seniority",
    "sentence",
    "separate",
    "separation",
    "separation of authorities",
    "sequence",
    "service promotion board",
    "short and long term",
    "short title",
    "seize power",
    "simple majority",
    "single member constituency",
    "sitting fees",
    "sitting",
    "sitting plan",
    "slip of tongue",
    "smuggle",
    "social and cultural committee",
    "social development",
    "social harmony",
    "social welfare",
    "socio-economy",
    "solution",
    "sovereign kingdom",
    "sove",
    "sovereign right",
    "speaker",
    "special committee",
    "special court",
    "special session",
    "special skill",
    "spiritual and secular  law",
    "spiritual heritage",
    "standard of conduct",
    "standing committee",
    "state action",
    "state affairs",
    "state function",
    "state guests",
    "state of the nation",
    "state visit",
    "statement of fact",
    "statute",
    "statutory authority",
    "statutory debate",
    "statutory order",
    "statutory review",
    "steady faith and commitment",
    "step down",
    "streamline",
    "strict command",
    "strict law",
    "strife",
    "sub-committee",
    "sub-division of village administra",
    "subject matter",
    "subject of discussion",
    "subject of dispute",
    "submission",
    "subordinate courts",
    "succession",
    "successor",
    "summary",
    "summary of deliberations",
    "summary of discussion",
    "suspension",
    "superannuation",
    "superseding",
    "supervision",
    "supplementary questions",
    "supplementary",
    "supplicate",
    "supporting evidence",
    "supreme commander",
    "supreme court",
    "supreme law",
    "surrounding environment",
    "surveyor-general",
    "suspect",
    "suspension of member",
    "symbol of unity",
    "system",
    "table officer",
    "tamper",
    "task force",
    "tenure",
    "term",
    "term of office",
    "terminology",
    "terms of reference",
    "terms of service",
    "territory",
    "testimony",
    "textual meaning",
    "the constitution",
    "theory of law",
    "third party",
    "third reading",
    "thorough investigation",
    "thought",
    "thought",
    "three branches of the government",
    "municipal council",
    "thumb print",
    "title",
    "top secret",
    "town",
    "traditional practice",
    "trafficking child",
    "transcribe",
    "transgression",
    "transparent",
    "treaty",
    "trespass",
    "trial",
    "tribunal",
    "two-third",
    "typing errors",
    "ultimate goal",
    "ultimate interest",
    "unanimous",
    "unanimous decision",
    "unanimously",
    "uncertain security",
    "unchangeable",
    "unconstitutional",
    "uncontested election",
    "under law",
    "undermine",
    "understanding",
    "undertaking",
    "undue burden",
    "undue delay",
    "unforgettable",
    "unicameral",
    "uniformity",
    "unilateral decision",
    "unique",
    "unity",
    "unlawful interferen",
    "unparalleled",
    "un-parliamentary language",
    "until universal existence",
    "unwavering fidelity",
    "update",
    "uprising",
    "valid reason",
    "variation",
    "vary",
    "venue",
    "verbatim",
    "verbatim",
    "vested interest",
    "veto power",
    "vibrant",
    "violation",
    "visit",
    "voluntary contribution",
    "voluntary resignation",
    "vote",
    "vote",
    "vote of confidence",
    "vote of no confidence",
    "voter",
    "voter",
    "voter photo identity card (vpic)",
    "voting rights",
    "warning",
    "wellbeing",
    "widespread",
    "willfully",
    "wise guidance",
    "wise leadership",
    "withdraw",
    "withdraw case",
    "witness",
    "working group",
    "writ",
    "written question",
    "yearly",
    "youth",
    "youth parliament",
  ];
}
